on:
  push:
    tags:
      - '*'


permissions:
  contents: write

name: build and publish python

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Print Event
        continue-on-error: true
        run: echo ${{ toJSON(github.event) }}
      - name: Get project path
        id: get-path
        run: |
          project_name=$(echo ${{ github.ref_name }} | cut -d "@" -f 1)
          "project_name=$project_name" >> $GITHUB_OUTPUT
          "project_path=python/$project_name" >> $GITHUB_OUTPUT
      - uses: actions/setup-python@v5
        id: cache
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Install dependencies
        working-directory: steps.get-path.outputs.project_path
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry install
        shell: bash
      - name: Build
        working-directory: steps.get-path.outputs.project_path
        id: build
        run: poetry build
#      - name: Publish
#        env:
#          project_name: ${{ steps.build.outputs.project_name }}
#        run: |
#          jf rt upload "python/$project_name/dist/*"


